using Playnite.SDK;
using Playnite.SDK.Models;
using Playnite.SDK.Plugins;
using System;
using System.Collections.Generic;
using System.IO; // Required for Directory operations
using System.Linq;
using System.Security.Cryptography; // Required for MD5 Hash
using System.Text;
using System.Windows.Controls;

namespace Monolith
{
    public class Monolith : LibraryPlugin
    {
        private static readonly ILogger logger = LogManager.GetLogger();
        private MonolithSettingsViewModel settings { get; set; }

        // Persist ID generated by Toolbox
        public override Guid Id { get; } = Guid.Parse("0846f275-5dcd-4ab4-8f93-267a098f2189");
        public override string Name => "Monolith"; // Name updated
        public override LibraryClient Client { get; } = new MonolithClient();

        public Monolith(IPlayniteAPI api) : base(api)
        {
            settings = new MonolithSettingsViewModel(this);
            Properties = new LibraryPluginProperties { HasSettings = true };
        }

        public override IEnumerable<GameMetadata> GetGames(LibraryGetGamesArgs args)
        {
            var games = new List<GameMetadata>();
            var scanner = new MonolithScanner();
            
            logger.Info("Monolith GetGames started.");
            
            // Get directories from settings
            var directoriesToScan = settings.Settings.ScanDirectories;

            // Fallback for testing if empty
            if (directoriesToScan == null || !directoriesToScan.Any())
            {
               logger.Info("No scan directories configured in settings. Checking common default paths...");
               directoriesToScan = new List<string>();
               
               if (Directory.Exists(@"C:\Games")) directoriesToScan.Add(@"C:\Games");
               if (Directory.Exists(@"D:\Games")) directoriesToScan.Add(@"D:\Games");
               if (Directory.Exists(@"E:\Games")) directoriesToScan.Add(@"E:\Games");
               
               if (!directoriesToScan.Any())
               {
                   logger.Info("No default game directories found either.");
                   return games;
               }
            }
            
            logger.Info($"Scanning {directoriesToScan.Count} directories.");

            foreach (var scanPath in directoriesToScan)
            {
                if (!Directory.Exists(scanPath))
                {
                    logger.Warn($"Scan path not found: {scanPath}");
                    continue;
                }

                try 
                {
                    // Call the scanner synchronously for now since GetGames is synchronous
                    var discoveredGames = scanner.ScanDirectoryAsync(scanPath).GetAwaiter().GetResult();

                    foreach (var d in discoveredGames)
                    {
                         games.Add(new GameMetadata
                         {
                             Name = d.Name,
                             GameId = GetDeterministicId(d.InstallDirectory), 
                             InstallDirectory = d.InstallDirectory,
                             IsInstalled = true,
                             Source = new MetadataNameProperty("Monolith"),
                             Platforms = new HashSet<MetadataProperty> { new MetadataSpecProperty("pc_windows") },
                             GameActions = new List<GameAction>
                             {
                                 new GameAction
                                 {
                                     Type = GameActionType.File,
                                     Path = d.ExecutablePath,
                                     IsPlayAction = true,
                                     Name = "Play"
                                 }
                             }
                         });
                    }
                }
                catch (Exception ex)
                {
                    logger.Error(ex, $"Error scanning path: {scanPath}");
                }
            }

            return games;
        }

        // Helper method to generate deterministic ID keeps the same
        private string GetDeterministicId(string path)
        {
            using (var md5 = MD5.Create())
            {
                var hash = md5.ComputeHash(Encoding.UTF8.GetBytes(path.ToLowerInvariant()));
                return new Guid(hash).ToString();
            }
        }

        public override ISettings GetSettings(bool firstRunSettings) => settings;
        public override UserControl GetSettingsView(bool firstRunSettings) => new MonolithSettingsView();
    }
}